### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by HetSP07** [SakhriHoussem/Classification-of-Satellite-images#1]
When i'm typing this code
`python dataSetGenerator.py  --path Desktop/SIRI-WHU --resize --resize_to 200`
 i'm getting this error 
```
def plotFiles(*path,xlabel='# epochs',ylabel='Error and Accu',reduce_each=False,autoClose=False,ff="None",save_as="plot",save_to="images"):
                             ^
SyntaxError: invalid syntax
```
any idea !!!

**Comment by SakhriHoussem** [comment]
There no need to use `plotfiles()` when you use this command line to execute `dataSetGenerator.py` 
If you costumize the code put more informations to can help you

 **to make think clear:** 
- first you must dowload the [SIRI-WHU DataSet](http://www.lmars.whu.edu.cn/prof_web/zhongyanfei/Code/Google_Dataset/Google%20dataset%20of%20SIRI-WHU_earth_im_tiff.7z)
- the extract **12class_tif** folder to the **Desktop**
- then rename it to **SIRI-WHU**
- and execute this line of commande
`python dataSetGenerator.py --path C:\Users\%USERPROFILE%\Desktop\SIRI-WHU --resize True --resize_to 200`
