### ISSUE TITLE
Confusion matrix

### ISSUE THREAD

**Issue by HetSP07** [SakhriHoussem/Classification-of-Satellite-images#2]
when I try to draw the confusion matrix I'm getting this error 
 
    File "confusion_matrix.py", line 54, in <module>
         if args.showPic: picShow(batch[:min_batch], labels[:min_batch], classes, None, prob)
    TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by SakhriHoussem** [comment]
- you have already weights for your datasets !!
- which dataset you use !!
- see if all the pictures have the same size

**Comment by HetSP07** [comment]
I used **UC-Merced LandUse** and I have the file `VGG19_UCMerced_LandUse.npy` for the weights and I resized the images 200*200 from the beginning.

**Comment by SakhriHoussem** [comment]
What command line you used to generate confusion matrix !!

this command line will  work perfectly for you if your dataset named **UCMerced_LandUse**
```bash
python confusion_matrix.py --dataset UCMerced_LandUse
```
